export interface Location {
  id?: number;
  name: string;
  description: string;
  latitude: number;
  longitude: number;
  created_by: number; // can be generated by map api or user
  created_at?: Date;
}

export interface Workout {
  id?: number;
  user_id: number;
  location_id: number;
  created_at?: Date;
}

export interface CreateWorkout {
  user_id: number;
  location_id?: number;
  name: string;
  description?: string;
  duration_minutes?: number;
  exercises: {
    exercise_id: number;
    sets: number;
    reps: number;
    weight?: number;
  }[];
}
